# Generated by Django 5.2 on 2025-05-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('valor', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'calificaciones',
                'ordering': ['valor'],
            },
        ),
    ]
