# Generated by Django 5.2 on 2025-05-29 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('valor', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('id_libro_fk', models.ForeignKey(db_column='id_libro_fk', on_delete=django.db.models.deletion.CASCADE, to='libros.librosmodel')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calificaciones',
                'ordering': ['valor'],
                'unique_together': {('usuario_creador', 'id_libro_fk')},
            },
        ),
    ]
