# Generated by Django 5.2 on 2025-05-24 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificaciones', '0001_initial'),
        ('libros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacionmodel',
            name='id_libro_fk',
            field=models.ForeignKey(db_column='id_libro_fk', on_delete=django.db.models.deletion.CASCADE, to='libros.librosmodel'),
        ),
        migrations.AddField(
            model_name='calificacionmodel',
            name='usuario_creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
