# Generated by Django 5.2 on 2025-05-24 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '__first__'),
        ('generos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
                ('id_autor_fk', models.ForeignKey(db_column='id_autor_fk', on_delete=django.db.models.deletion.CASCADE, to='autores.autormodel')),
                ('id_genero_fk', models.ForeignKey(db_column='id_genero_fk', on_delete=django.db.models.deletion.CASCADE, to='generos.generomodel')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'libros',
                'ordering': ['id'],
            },
        ),
    ]
