# Generated by Django 5.2 on 2025-05-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librosmodel',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='libros_epub/'),
        ),
    ]
